# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QLineEdit,
    QPushButton, QSizePolicy, QWidget)

class Ui_Calculadora(object):
    def setupUi(self, Calculadora):
        if not Calculadora.objectName():
            Calculadora.setObjectName(u"Calculadora")
        Calculadora.resize(237, 323)
        Calculadora.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.groupBox = QGroupBox(Calculadora)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 100, 211, 211))
        self.groupBox.setStyleSheet(u"background-color: rgb(240, 240, 240);")
        self.BtnIgual = QPushButton(self.groupBox)
        self.BtnIgual.setObjectName(u"BtnIgual")
        self.BtnIgual.setGeometry(QRect(110, 170, 91, 31))
        self.BtnIgual.setStyleSheet(u"background-color: rgb(254, 255, 189);")
        self.Btn7 = QPushButton(self.groupBox)
        self.Btn7.setObjectName(u"Btn7")
        self.Btn7.setGeometry(QRect(10, 50, 41, 31))
        self.Btn7.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn8 = QPushButton(self.groupBox)
        self.Btn8.setObjectName(u"Btn8")
        self.Btn8.setGeometry(QRect(60, 50, 41, 31))
        self.Btn8.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn9 = QPushButton(self.groupBox)
        self.Btn9.setObjectName(u"Btn9")
        self.Btn9.setGeometry(QRect(110, 50, 41, 31))
        self.Btn9.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn4 = QPushButton(self.groupBox)
        self.Btn4.setObjectName(u"Btn4")
        self.Btn4.setGeometry(QRect(10, 90, 41, 31))
        self.Btn4.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn5 = QPushButton(self.groupBox)
        self.Btn5.setObjectName(u"Btn5")
        self.Btn5.setGeometry(QRect(60, 90, 41, 31))
        self.Btn5.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn6 = QPushButton(self.groupBox)
        self.Btn6.setObjectName(u"Btn6")
        self.Btn6.setGeometry(QRect(110, 90, 41, 31))
        self.Btn6.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn1 = QPushButton(self.groupBox)
        self.Btn1.setObjectName(u"Btn1")
        self.Btn1.setGeometry(QRect(10, 130, 41, 31))
        self.Btn1.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn2 = QPushButton(self.groupBox)
        self.Btn2.setObjectName(u"Btn2")
        self.Btn2.setGeometry(QRect(60, 130, 41, 31))
        self.Btn2.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.Btn3 = QPushButton(self.groupBox)
        self.Btn3.setObjectName(u"Btn3")
        self.Btn3.setGeometry(QRect(110, 130, 41, 31))
        self.Btn3.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.btn0 = QPushButton(self.groupBox)
        self.btn0.setObjectName(u"btn0")
        self.btn0.setGeometry(QRect(60, 170, 41, 31))
        self.btn0.setStyleSheet(u"background-color: rgb(226, 226, 226);")
        self.btnPunt = QPushButton(self.groupBox)
        self.btnPunt.setObjectName(u"btnPunt")
        self.btnPunt.setGeometry(QRect(10, 170, 41, 31))
        self.btnPunt.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.BtnMult = QPushButton(self.groupBox)
        self.BtnMult.setObjectName(u"BtnMult")
        self.BtnMult.setGeometry(QRect(160, 50, 41, 31))
        self.BtnMult.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.BtnSum = QPushButton(self.groupBox)
        self.BtnSum.setObjectName(u"BtnSum")
        self.BtnSum.setGeometry(QRect(160, 130, 41, 31))
        self.BtnSum.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.BtnRest = QPushButton(self.groupBox)
        self.BtnRest.setObjectName(u"BtnRest")
        self.BtnRest.setGeometry(QRect(160, 90, 41, 31))
        self.BtnRest.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.BtnDiv = QPushButton(self.groupBox)
        self.BtnDiv.setObjectName(u"BtnDiv")
        self.BtnDiv.setGeometry(QRect(160, 10, 41, 31))
        self.BtnDiv.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn00 = QPushButton(self.groupBox)
        self.btn00.setObjectName(u"btn00")
        self.btn00.setGeometry(QRect(60, 10, 41, 31))
        self.btn00.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btnC = QPushButton(self.groupBox)
        self.btnC.setObjectName(u"btnC")
        self.btnC.setGeometry(QRect(110, 10, 41, 31))
        self.btnC.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btnAC = QPushButton(self.groupBox)
        self.btnAC.setObjectName(u"btnAC")
        self.btnAC.setGeometry(QRect(10, 10, 41, 31))
        self.btnAC.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.entrada = QLineEdit(Calculadora)
        self.entrada.setObjectName(u"entrada")
        self.entrada.setGeometry(QRect(10, 10, 211, 71))
        font = QFont()
        font.setFamilies([u"Yu Gothic Medium"])
        font.setPointSize(48)
        self.entrada.setFont(font)
        self.entrada.setCursor(QCursor(Qt.ArrowCursor))
        self.entrada.setEchoMode(QLineEdit.Normal)
        self.entrada.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.retranslateUi(Calculadora)

        QMetaObject.connectSlotsByName(Calculadora)
    # setupUi

    def retranslateUi(self, Calculadora):
        Calculadora.setWindowTitle(QCoreApplication.translate("Calculadora", u"Calculadora", None))
        self.groupBox.setTitle("")
        self.BtnIgual.setText(QCoreApplication.translate("Calculadora", u"=", None))
        self.Btn7.setText(QCoreApplication.translate("Calculadora", u"7", None))
        self.Btn8.setText(QCoreApplication.translate("Calculadora", u"8", None))
        self.Btn9.setText(QCoreApplication.translate("Calculadora", u"9", None))
        self.Btn4.setText(QCoreApplication.translate("Calculadora", u"4", None))
        self.Btn5.setText(QCoreApplication.translate("Calculadora", u"5", None))
        self.Btn6.setText(QCoreApplication.translate("Calculadora", u"6", None))
        self.Btn1.setText(QCoreApplication.translate("Calculadora", u"1", None))
        self.Btn2.setText(QCoreApplication.translate("Calculadora", u"2", None))
        self.Btn3.setText(QCoreApplication.translate("Calculadora", u"3", None))
        self.btn0.setText(QCoreApplication.translate("Calculadora", u"0", None))
        self.btnPunt.setText(QCoreApplication.translate("Calculadora", u".", None))
        self.BtnMult.setText(QCoreApplication.translate("Calculadora", u"x", None))
        self.BtnSum.setText(QCoreApplication.translate("Calculadora", u"+", None))
        self.BtnRest.setText(QCoreApplication.translate("Calculadora", u"-", None))
        self.BtnDiv.setText(QCoreApplication.translate("Calculadora", u"/", None))
        self.btn00.setText(QCoreApplication.translate("Calculadora", u"00", None))
        self.btnC.setText(QCoreApplication.translate("Calculadora", u"C", None))
        self.btnAC.setText(QCoreApplication.translate("Calculadora", u"AC", None))
        self.entrada.setText("")
        self.entrada.setPlaceholderText(QCoreApplication.translate("Calculadora", u"0", None))
    # retranslateUi

